sVresources/views.py
# -*- coding: utf-8 -*-
# Copyright (c) 2017 Renat R. Dusaev <crank@qcrypt.org>
# Author: Renat R. Dusaev <crank@qcrypt.org>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from __future__ import print_function
from sVresources import get_app
from flask import Blueprint, render_template, url_for, g

bp = Blueprint( 'sVresources', __name__,
                template_folder='templates',
                static_folder='static')

@bp.route('/')
def index_view():
    return render_template('layouts/main.html',
                            loadedBlueprints=get_app().loadedBlueprints)

@bp.route('/about/')
def about_view():
    return render_template('pages/about.html')

# Helper function
def has_no_empty_params(rule):
    defaults = rule.defaults if rule.defaults is not None else ()
    arguments = rule.arguments if rule.arguments is not None else ()
    return len(defaults) >= len(arguments)


@bp.route('/routes/')
def routes():
    getLinks = []
    postLinks = []
    for rule in get_app().url_map.iter_rules():
        # Filter out rules we can't navigate to in a browser
        # and rules that require parameters
        if "GET" in rule.methods:
            if has_no_empty_params(rule):
                url = url_for(rule.endpoint, **(rule.defaults or {}))
                getLinks.append((url, rule.endpoint))
            else:
                getLinks.append((rule.rule, "(endpoint unresolved)"))
        elif "POST" in rule.methods:
            if has_no_empty_params(rule):
                url = url_for(rule.endpoint, **(rule.defaults or {}))
                postLinks.append((url, rule.endpoint))
            else:
                postLinks.append((rule.rule, "(endpoint unresolved)"))
    # links is now a list of url, endpoint tuples
    return render_template( 'pages/routes.html',
                        getLinks=getLinks,
                        postLinks=postLinks )

@bp.app_errorhandler(404)
def page_not_found(e):
    return render_template('errors/404.html'), 404

sVresources_Blueprint = bp

sVresources/templates/layouts/form.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body class="form-only-page">

  <div class="container">

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning fade in">
            <a class="close" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>
  
  <!-- Google Analytics - Change UA-XXXXX-X to be your site's ID -->
  <script>
  window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  </script>

</body>
</html>

sVresources/templates/layouts/main.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{{config.sitename}}{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
{% block suppStyles %}{% endblock %}
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

{% block suppHeadContent %} {% endblock %}

</head>
<body>

  <!-- Wrap all page content here -->
  <div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{config.siteurl}}/">{{config.sitename}}</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {#<li {% if request.endpoint == 'home' %} class="active" {% endif %}><a href="{{ url_for('sVresources.index_view') }}">Home</a></li>#}
            <li {% if request.endpoint == 'about' %} class="active" {% endif %}><a href="{{ url_for('sVresources.about_view') }}">About</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">Modules <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('sVresources.routes') }}">View All Routes</a></li>
                {#<li><a href="{{ url_for('sVlogging.logs') }}">Dump System Logs</a></li>#}
                {#<li class="divider"></li>
                <li class="dropdown-header">castlib2</li>
                <li><a>Observe Data Chunks</a></li>
                <li class="dropdown-header">extGDML</li>
                <li><a>Observe Geometry</a></li>#}
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            {#<li><a href="#">Signup</a></li>
            <li><a href="#">Login</a></li>#}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <main id="content" role="main" class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-block alert-error fade in">
              <a class="close" data-dismiss="alert">&times;</a>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}
      <h1>Loaded Blueprints</h1>
      <p>Here is a list of loaded Flask “blueprints” — the modules providing acces to the certain functionality.</p>
      <p>Each blueprint usually submits a group of artifacts and data categories.</p>
      <ul>
        {% for bpe in loadedBlueprints %}
          <li><code>{{bpe[0]}}</code> … <tt><b>{{bpe[1]}}</b></tt></li>
        {% endfor %}
      <ul>
      {% endblock %}
      
    </main>

  </div>

  <div id="footer">
    <div class="container">
      <p>CERN / NA64 Collaboration &copy; All Rights Reserved.</p>
      {% block footer %}{% endblock %}
    </div>
  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>
  {% block suppScripts %}{% endblock %}
  {#<!-- Google Analytics - Change UA-XXXXX-X to be your site's ID -->
  <script>
  window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  </script>#}
</body>
</html>